export enum SocialMediaEnum {
  facebook = 1,
  youTube = 2,
  whatsapp = 3,
  instagram = 4,
  weChat = 5,
  tikTok = 6,
  snapchat = 7,
  twitter = 8,
  linkedIn = 9,
  reddit = 10,
  pinterest = 11,
  telegram = 12,
  discord = 13,
  tinder = 14,
  line = 15,
  clubhouse = 16,
  twitch = 17,
}
