name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker-compose build
          docker-compose push

      - name: SSH into server and pull changes
        uses: appleboy/ssh-action@master
        with:
          host: 195.201.30.246
          username: root
          password: ifAC7tcrtug9RqsCvVJ4
          script: |
            cd tonet/web-app
            docker-compose pull
            docker-compose up -d
